api/config/routes.rb
Rails.application.routes.draw do
  scope :api do
    scope :v1 do
      # admin
      namespace :admin do
        resources :users do
          get 'sections', on: :member
        end
      end
      # ログイン処理
      get '/login', to: 'sessions#new'
      post '/login', to: 'sessions#create'
      delete '/logout', to: 'sessions#destroy'
      # TODO
      root to: 'tasks#index'
      resources :tasks do
        post :confirm, action: :confirm_new, on: :new
        post :import, on: :collection
      end
      # task_type
      resources :task_types

      # 日報作成
      resources :daily_report, only: :create
    end
  end
end

api/app/models/task.rb
class Task < ApplicationRecord
  has_one_attached :image

  enum status: { backlog: 'backlog', wip: 'wip', complete: 'complete' }, _prefix: true

  def self.ransackable_attributes(_auth_object = nil)
    %w[name task_type_id status created_at]
  end

  def self.ransackable_associations(_auth_object = nil)
    []
  end

  def self.csv_attributes
    %w[name description created_at updated_at]
  end

  def self.generate_csv
    CSV.generate(headers: true) do |csv|
      csv << csv_attributes
      all.each do |task|
        csv << csv_attributes.map { |attr| task.send(attr) }
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      task = new
      task.attributes = row.to_hash.slice(*csv_attributes)
      task.save!
    end
  end

  before_validation :set_nameless_name
  validates :name, presence: true
  validates :name, length: { maximum: 30 }
  validate :validate_name_not_including_comma

  belongs_to :user
  belongs_to :task_type
  belongs_to :task_status

  scope :recent, -> { order(created_at: :desc) }

  private

  def set_nameless_name
    self.name = '名前なし' if name.blank?
  end

  def validate_name_not_including_comma
    errors.add(:name, 'にカンマを含めることはできません') if name&.include?(',')
  end
end

api/app/models/task_type.rb
class TaskType < ApplicationRecord
  validates :name, presence: true

  has_many :tasks
end

api/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  def index
    tasks = Task.all
    render json: tasks
  end

  def show; end

  def new
    task = Task.new
    render status: :ok, json: { message: 'success', data: tasks, errors: [] }
  end

  def edit; end

  def create
    task = Task.new(task_params.merge(user_id: current_user.id))
    if task.save
      # TaskMailer.creation_email(@task).deliver_now
      # SampleJob.perform_later
      render status: :ok, json: task
    else
      render status: 500, json: { message: 'error', data: nil, errors: ['Internal Server Error'] }
    end
  end

  def update
    if task.update!(task_params)
      render status: :ok, json: task
    else
      render status: 500, json: { message: 'error', data: nil, errors: ['Internal Server Error'] }
    end
  end

  def destroy
    if @task.destroy
      render status: :ok
    else
      render status: 500, json: { message: 'error', data: nil, errors: ['Internal Server Error'] }
    end
  end

  # def import
  #   current_user.tasks.import(params[:file])
  #   redirect_to tasks_url, notice: 'タスクを追加しました'
  # end

  private

  def task_params
    params.permit(:name, :task_type_id, :status, :description, :image)
  end

  # taskを取得する
  def set_task
    task = current_user.tasks.find(params[:id])
  end
end

api/app/helpers/tasks_helper.rb
module TasksHelper
end

api/app/views/tasks/_form.html.slim
- if task.errors.present?
  ul#error_explanation
    - task.errors.full_messages.each do |message|
      li = message

= form_with model: task, local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'task_name'
  .form-group
    = f.label :task_type_id
    = f.collection_select :task_type_id, @task_types, :id, :name, {prompt: "種類を選択してください"}, class: 'form-select'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'
  .form-group
    = f.label :status
    = f.select :status, Task.statuses.keys.map {|k| [I18n.t("enums.task.status.#{k}"), k]}, {}, class: 'form-select'
  .form-group
    = f.label :image
    = f.file_field :image, class: 'form-control'
  = f.submit nil, class: 'btn btn-primary mt-3'

api/app/views/tasks/confirm_new.slim
h1.mt-3 登録内容の確認

= form_with model: @task, local: true do |f|
  table.table.table-hover
    tbody
      tr
        th = Task.human_attribute_name(:name)
        td = @task.name
        = f.hidden_field :name
      tr
        th = Task.human_attribute_name(:description)
        td = simple_format(@task.description)
        = f.hidden_field :description
  = f.submit '戻る', name: 'back', class: 'btn btn-secondary me-3'
  = f.submit '登録', class: 'btn btn-primary'

api/app/views/tasks/destroy.js.erb
document.querySelector("#task-<%= @task.id %>").style.display = 'none';

var message = document.createElement('p');
message.innerText = 'タスク「<%= @task.name %>」を削除しました。残りのタスクは<%= current_user.tasks.count %>件です。';
document.querySelector('table').insertAdjacentElement('beforebegin', message);

api/app/views/tasks/edit.html.slim
h1.mt-3 タスクの編集

.nav.justify-content.end
  = link_to '一覧', tasks_path, class: 'nav-link'

= render partial: 'form', locals: { task: @task }

api/app/views/tasks/index.html.slim
h1.mt-3.mt-3 タスク一覧

= search_form_for @q, class: 'mb-5' do |f|
  .form-group.row.my-3
    = f.label :name_cont, '名称', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :name_cont, class: 'form-control'
  .form-group.row.my-3
    = f.label :task_type_id_eq, '種類', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.select :task_type_id_eq, TaskType.all.map{|c|[c[:name], c[:id]]}, {include_blank: true}, class: 'form-select'
  .form-group.row.my-3
    = f.label :status_eq, '進捗', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.select :status_eq, Task.statuses.keys.map {|k| [I18n.t("enums.task.status.#{k}"), k]}, {include_blank: true}, class: 'form-select'
  .form-group.row.my-3
    = f.label :name_cont, '登録日時', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :created_at_gteq, class: 'form-control'
  .form-group.my-3
    = f.submit class: 'btn btn-outline-primary'


= link_to '新規登録', new_task_path, class: 'btn btn-primary mb-3'
= link_to '日報作成', daily_report_path, class: 'btn btn-primary ms-3 mb-3'

.mb-3
  = paginate @tasks
  = page_entries_info @tasks

table.table.table-hover
  thead.thead-default
    tr
      th = sort_link(@q, :name)
      th
        = Task.human_attribute_name(:task_type_id)
        = link_to "新規", new_task_type_path, class: 'btn btn-sm btn-primary ms-3'
      th = Task.human_attribute_name(:status)
      th = Task.human_attribute_name(:created_at)
      th
    tbody
      - @tasks.each do |task|
        tr id="task-#{task.id}"
          td = link_to task.name, task
          td = @task_types.where(id: task.task_type_id).first.name
          td = task.status_i18n
          td = task.created_at
          td
            = link_to '編集', edit_task_path(task), class: 'btn btn-primary me-3'
            = link_to '削除', task, method: :delete, remote: true, data: {confirm: "タスク「#{task.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger delete'

= link_to 'エクスポート', tasks_path(format: :csv), class: 'btn btn-primary mb-3'

= form_tag import_tasks_path, multipart: true, class: 'mb-3' do
  = file_field_tag :file_field
  = submit_tag "インポート", class: 'btn btn-primary'

api/app/views/tasks/new.html.slim
h1.mt-3 タスクの新規登録

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'

= render partial: 'form', locals: { task: @task }

/ - if @task.errors.present?
/   ul#error_explanation
/     - @task.errors.full_messages.each do |message|
/       li = message

/ = form_with model: @task, local: true, url: confirm_new_task_path do |f|
/     .form-group
/       = f.label :name
/       = f.text_field :name, class: 'form-control', id: 'task_name'
/     .form-group
/       = f.label :description
/       = f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'
/     = f.submit nil, class: 'btn btn-primary'

api/app/views/tasks/show.html.slim
h1.mt-3 タスクの詳細

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= Task.human_attribute_name(:id)
      td= @task.id
    tr
      th= Task.human_attribute_name(:name)
      td= @task.name
    tr
      th= Task.human_attribute_name(:task_type_id)
      td= @task_types.where(id: @task.task_type_id).first.name
    tr
      th= Task.human_attribute_name(:status)
      td= @task.status_i18n
    tr
      th= Task.human_attribute_name(:description)
      td= auto_link(simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: "div"))
    tr
      th= Task.human_attribute_name(:created_at)
      td= @task.created_at
    tr
      th= Task.human_attribute_name(:updated_at)
      td= @task.updated_at
= link_to '編集', edit_task_path, class: 'btn btn-primary me-3'
= link_to '削除', @task, method: :delete, data: {confirm: "タスク「#{@task.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'