api/config/routes.rb
Rails.application.routes.draw do
  scope :api do
    scope :v1 do
      # admin
      namespace :admin do
        resources :users do
          get 'sections', on: :member
        end
      end
      # ログイン処理
      get '/login', to: 'sessions#new'
      post '/login', to: 'sessions#create'
      delete '/logout', to: 'sessions#destroy'
      # TODO
      root to: 'tasks#index'
      resources :tasks do
        post :confirm, action: :confirm_new, on: :new
        post :import, on: :collection
      end
      # task_type
      resources :task_types

      # 日報作成
      resources :daily_report, only: :create
    end
  end
end

api/app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Todo
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand.ms-3 Todo

      ul.navbar-nav.ms-auto
        - if current_user
          li.nav-item= link_to 'タスク一覧', tasks_path, class: 'nav-link'
          - if current_user.admin?
            li.nav-item= link_to 'ユーザー一覧', admin_users_path, class: 'nav-link'
          li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
        - else
          li.nav-item= link_to 'ログイン', login_path, class: 'nav-link'
    .container
      - if flash.notice.present?
        .alert.alert-success=flash.notice
      = yield