api/config/routes.rb
Rails.application.routes.draw do
  scope :api do
    scope :v1 do
      # admin
      namespace :admin do
        resources :users do
          get 'sections', on: :member
        end
      end
      # ログイン処理
      get '/login', to: 'sessions#new'
      post '/login', to: 'sessions#create'
      delete '/logout', to: 'sessions#destroy'
      # TODO
      root to: 'tasks#index'
      resources :tasks do
        post :confirm, action: :confirm_new, on: :new
        post :import, on: :collection
      end
      # task_type
      resources :task_types

      # 日報作成
      resources :daily_report, only: :create
    end
  end
end

api/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :tasks

  belongs_to :department
  belongs_to :section
end

api/app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin
  before_action :set_user, only: %i[show edit update destroy]

  def new
    user = User.new
    render status: :ok, json: user
  end

  def edit; end

  def show; end

  def index
    users = User.all
    render status: :ok, json: users
  end

  def create
    user = User.new(user_params)
    if user.save
      render status: :ok, json: user
    else
      render status: 500, json: { message: 'Internal Server Error' }
    end
  end

  def update
    if user.update(user_params)
      render status: :ok, json: user
    else
      render status: 500, json: { message: 'Internal Server Error' }
    end
  end

  def destroy
    if user.destroy
      render status: :ok
    else
      render status: 500, json: { message: 'Internal Server Error' }
    end
  end

  private

  def user_params
    # 　必要なやつだけ取ってくる
    params.permit(:name, :email, :admin, :password, :password_confirmation, :department_id, :section_id)
  end

  def require_admin
    redirect_to root_url unless current_user.admin?
  end

  def set_user
    user = User.find(params[:id])
  end
end

api/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

api/app/views/admin/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
    - user.errors.full_messages.each do |message|
      li = message

= form_with model: [:admin, user], local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-check
    = f.label :admin, class: 'form-check-label' do
      = f.check_box :admin, class: 'form-check-input'
      | 管理者権限
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード（確認）'
    = f.password_field :password_confirmation, class: 'form-control'
  .form-group
    = f.label :department_id, '部署'
    = f.collection_select :department_id, departments, :id, :name, {prompt: "部署を選択してください"}, class: 'form-select'
  .form-group
    = f.label :section_id, 'グループ'
    - if !user.department.nil?
      = f.collection_select :section_id, user.department.sections, :id, :name, {prompt: "false"}, class: 'form-select'
      / = render partial: 'section', locals: {section: user.department.sections}
    - else
      = f.collection_select :section_id, @sections, :id, :name, {prompt: "グループを選択してください"}, class: 'form-select'
  = f.submit '登録する', class: 'btn btn-primary mt-3'

api/app/views/admin/users/_section.html.slim
/  = f.collection_select :section_id, section, :id, :name, {prompt: "false"}, class: 'form-select'

api/app/views/admin/users/edit.html.slim
h1.mt-3 ユーザーの編集
.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'
= render partial: 'form', locals: {user: @user, departments: @departments}

api/app/views/admin/users/index.html.slim
h1.mt-3 ユーザー一覧

= link_to '新規登録', new_admin_user_path, class: 'btn btn-primary my-3'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th = User.human_attribute_name(:name)
      th = User.human_attribute_name(:email)
      th = User.human_attribute_name(:admin)
      th = User.human_attribute_name(:created_at)
      th = User.human_attribute_name(:updated_at)

    tbody
      - @users.each do |user|
        tr
          td = link_to user.name, [:admin, user]
          td = user.email
          td = user.admin? ? 'あり' : 'なし'
          td = user.created_at
          td = user.updated_at
          td
            = link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary me-3'
            = link_to '削除', [:admin, user], method: :delete, data: {confirm: "ユーザー「#{user.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'

/ 開発本部 ｲﾝﾌﾗ開発部
/ 		ｲﾝﾌﾗｸﾞﾙｰﾌﾟ
/ 開発本部 開発部
/ 		開発1ｸﾞﾙｰﾌﾟ
/ 		開発3ｸﾞﾙｰﾌﾟ
/ 		開発4ｸﾞﾙｰﾌﾟ
/ 		開発5ｸﾞﾙｰﾌﾟ
/ 		開発6ｸﾞﾙｰﾌﾟ
/ 		開発7ｸﾞﾙｰﾌﾟ
/ 広告事業本部
/ 広告事業本部 ｱﾄﾞﾌﾟﾗｯﾄﾌｫｰﾑ部
/   ｱﾄﾞｵﾍﾟﾚｰｼｮﾝｸﾞﾙｰﾌﾟ
/   ｺﾝｻﾙﾀﾝﾄｸﾞﾙｰﾌﾟ
/   ｺﾝｻﾙﾀﾝﾄｸﾞﾙｰﾌﾟ ｺﾝｻﾙ1ﾁｰﾑ
/   ｺﾝｻﾙﾀﾝﾄｸﾞﾙｰﾌﾟ ｺﾝｻﾙ2ﾁｰﾑ
/   ﾃﾞｨﾚｸﾀｰｸﾞﾙｰﾌﾟ
/ 広告事業本部 ｴﾘｱ広告部
/   ﾃﾞｨﾚｸﾀｰｸﾞﾙｰﾌﾟ
/ 広告事業本部 ﾒﾃﾞｨｱｺﾝｻﾙﾃｨﾝｸﾞ部
/   ｺﾝｻﾙｸﾞﾙｰﾌﾟ ｺﾝｻﾙ1ﾁｰﾑ
/   ｺﾝｻﾙｸﾞﾙｰﾌﾟ ｺﾝｻﾙ2ﾁｰﾑ
/   事業推進ｸﾞﾙｰﾌﾟ
/ 広告事業本部 ﾒﾃﾞｨｱ企画部
/   ｵﾍﾟﾚｰｼｮﾝｸﾞﾙｰﾌﾟ
/   ﾒﾃﾞｨｱｸﾞﾙｰﾌﾟ
/   ﾒﾃﾞｨｱｸﾞﾙｰﾌﾟ ｺﾝｻﾙﾁｰﾑ
/   ﾒﾃﾞｨｱｸﾞﾙｰﾌﾟ ﾒﾃﾞｨｱﾁｰﾑ
/   ﾒﾃﾞｨｱｾｰﾙｽｸﾞﾙｰﾌﾟ 1ﾁｰﾑ
/ 広告事業本部 営業企画部
/   ｱｼｽﾀﾝﾄｸﾞﾙｰﾌﾟ ｱｼｽﾀﾝﾄﾁｰﾑ
/   ｾｰﾙｽ1ｸﾞﾙｰﾌﾟ ｾｰﾙｽ1ﾁｰﾑ
/   ｾｰﾙｽ2ｸﾞﾙｰﾌﾟ
/   ｾｰﾙｽ2ｸﾞﾙｰﾌﾟ ｾｰﾙｽ2ﾁｰﾑ
/   ｾｰﾙｽ2ｸﾞﾙｰﾌﾟ ｾｰﾙｽ3ﾁｰﾑ
/   ｾｰﾙｽ3ｸﾞﾙｰﾌﾟ
/   ｾｰﾙｽ3ｸﾞﾙｰﾌﾟ ｾｰﾙｽ4ﾁｰﾑ
/   ｾｰﾙｽ3ｸﾞﾙｰﾌﾟ ｾｰﾙｽ5ﾁｰﾑ
/   ｾｰﾙｽ3ｸﾞﾙｰﾌﾟ ｾｰﾙｽ6ﾁｰﾑ
/ 事業統括本部 事業開発部
/ 	事業開発ｸﾞﾙｰﾌﾟ
/ 事業統括本部 社長室
/ 事業統括本部 制作部
/ 	制作ｸﾞﾙｰﾌﾟ
/ 事業統括本部 統括部
/ 	統括ｸﾞﾙｰﾌﾟ 統括ﾁｰﾑ
/ 人事総務部
/ 	人事総務部付 休職

api/app/views/admin/users/new.html.slim
h1.mt-3 ユーザー登録

.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'

= render partial: 'form', locals: {user: @user, departments: @departments}

/ =form_with model: [:admin, @user], local: true do |f|
/   .form-group
/     = f.label :name, '名前'
/     = f.text_field :name, class: 'form-control'
/   .form-group
/     = f.label :email, 'メールアドレス'
/     = f.text_field :email, class: 'form-control'
/   .form-check
/     = f.label :admin, class: 'form-check-label' do
/       = f.check_box :admin, class: 'form-check-input'
/       | 管理者権限
/   .form-group
/     = f.label :password, 'パスワード'
/     = f.password_field :password, class: 'form-control'
/   .form-group
/     = f.label :password_confirmation, 'パスワード（確認）'
/     = f.password_field :password_confirmation, class: 'form-control'
/   = f.submit '登録する', class: 'btn btn-primary'

api/app/views/admin/users/sections.js.erb
<%# document.getElementById("user_section_id").innerHTML(<%= escape_javascript(options_from_collection_for_select(@section)) %>
$("#user_section_id").html("<%= escape_javascript(options_from_collection_for_select(@sections, :id, :name)) %>");

api/app/views/admin/users/show.html.slim
h1.mt-3 ユーザーの詳細

.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= User.human_attribute_name(:id)
      td= @user.id
    tr
      th= User.human_attribute_name(:name)
      td= @user.name
    tr
      th= User.human_attribute_name(:email)
      td= @user.email
    tr
      th= User.human_attribute_name(:admin)
      td= @user.admin? ? 'あり' : 'なし'
    tr
      th= User.human_attribute_name(:created_at)
      td= @user.created_at
    tr
      th= User.human_attribute_name(:updated_at)
      td= @user.updated_at

= link_to '編集', edit_admin_user_path, class: 'btn btn-primary me-3'
= link_to '削除', [:admin, @user], method: :delete, data: {confirm: "ユーザー#{@user.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'