api/config/routes.rb
Rails.application.routes.draw do
  scope :api do
    scope :v1 do
      # admin
      namespace :admin do
        resources :users do
          get 'sections', on: :member
        end
      end
      # ログイン処理
      get '/login', to: 'sessions#new'
      post '/login', to: 'sessions#create'
      delete '/logout', to: 'sessions#destroy'
      # TODO
      root to: 'tasks#index'
      resources :tasks do
        post :confirm, action: :confirm_new, on: :new
        post :import, on: :collection
      end
      # task_type
      resources :task_types

      # 日報作成
      resources :daily_report, only: :create
    end
  end
end

api/app/controllers/task_types_controller.rb
class TaskTypesController < ApplicationController
  before_action :set_task_type, only: %i[show edit update destroy]
  def index
    task_types = TaskType.all
    render status: :ok, json: task_types
  end

  def show; end

  def new
    task_type = TaskType.new
    render status: :ok, json: task_type
  end

  def edit; end

  def create
    task_type = TaskType.new(task_type_params)
    if task_type.save
      render status: :ok, json: task_type
    else
      render status: 500, json: { message: 'Internal Server Error' }
    end
  end

  def update
    if task_type.update(task_type_params)
      render status: :ok, json: task_type
    else
      render status: 500, json: { message: 'Internal Server Error' }
    end
  end

  def destroy
    if task_type.destroy
      render status: :ok
    else
      render status: 500, json: { message: 'Internal Server Error' }
    end
  end

  private

  def task_type_params
    params.permit(:name)
  end

  def set_task_type
    @task_type = TaskType.find(params[:id])
  end
end

api/app/helpers/task_types_helper.rb
module TaskTypesHelper
end

api/app/views/task_types/_form.html.slim
- if task_type.errors.present?
  ul#error_explanation
    - task_type.errors.full_messages.each do |message|
      li = message

= form_with model: task_type, local: true do |f|
    .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control', id: 'task_type_name'
    = f.submit nil, class: 'btn btn-primary mt-3'

api/app/views/task_types/edit.html.slim
h1.mt-3 タスクの種類の編集

.nav.justify-content.end
  = link_to '一覧', task_types_path, class: 'nav-link'

= render partial: 'form', locals: { task_type: @task_type }

api/app/views/task_types/index.html.slim
h1.mt-3.mt-3 タスクの種類一覧

= link_to '新規登録', new_task_type_path, class: 'btn btn-primary mb-3'

.mb-3
  = paginate @task_types
  = page_entries_info @task_types

table.table.table-hover
  thead.thead-default
    tr
      th = sort_link(@q, :name)
      th = TaskType.human_attribute_name(:created_at)
      th
    tbody
      - @task_types.each do |task_type|
        tr id="task-type-#{task_type.id}"
          td = link_to task_type.name, task_type
          td = task_type.created_at
          td
            = link_to '編集', edit_task_type_path(task_type), class: 'btn btn-primary me-3'
            = link_to '削除', task_type, method: :delete, remote: true, data: {confirm: "タスク「#{task_type.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger delete'

api/app/views/task_types/new.html.slim
h1.mt-3 タスクの種類 新規登録

.nav.justify-content-end
  = link_to '一覧', task_types_path, class: 'nav-link'

= render partial: 'form', locals: { task_type: @task_type }

/ - if @task.errors.present?
/   ul#error_explanation
/     - @task.errors.full_messages.each do |message|
/       li = message

/ = form_with model: @task, local: true, url: confirm_new_task_path do |f|
/     .form-group
/       = f.label :name
/       = f.text_field :name, class: 'form-control', id: 'task_name'
/     .form-group
/       = f.label :description
/       = f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'
/     = f.submit nil, class: 'btn btn-primary'

api/app/views/task_types/show.html.slim
h1.mt-3 タスクの種類の詳細

.nav.justify-content-end
  = link_to '一覧', task_types_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= TaskType.human_attribute_name(:id)
      td= @task_type.id
    tr
      th= TaskType.human_attribute_name(:name)
      td= @task_type.name
    tr
      th= TaskType.human_attribute_name(:created_at)
      td= @task_type.created_at
    tr
      th= TaskType.human_attribute_name(:updated_at)
      td= @task_type.updated_at
= link_to '編集', edit_task_type_path, class: 'btn btn-primary me-3'
= link_to '削除', @task_type, method: :delete, data: {confirm: "タスク「#{@task_type.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'